feature: added keyboard and some screenreader functionality to checkb…
fntechgit/schedule-filter-widget pull request #6
Opened 2022-03-04 16:03 UTC by dequeMai

Adding keyboard functionality to the input boxes and the headers of the different filters.
Changed the custom divs into semantic html to better supper a11y

We will continue working on the combo box issue as that's been a bit more complicated

![image](https://user-images.githubusercontent.com/82385808/156797397-c198a9db-28c0-4a8d-9bc2-579a8099e370.png)

2022-03-04 16:55 UTC, santipalenque commented on src/components/filter-checkbox/index.js
> +            {/* <div className={wrapperClass} style={wrapperStyles} data-testid="checkbox">
please remove comments

2022-03-04 17:03 UTC, dequeMai commented
Apologies - I thought I did that already. Just forgot to push it out.

On Fri, Mar 4, 2022 at 10:55 AM Santi ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/components/filter-checkbox/index.js
> <https://github.com/fntechgit/schedule-filter-widget/pull/6#discussion_r819738123>
> :
>
> > @@ -12,11 +12,18 @@ const FilterCheckbox = ({ option, applyColors, selected, showCount, onFilterChan
>
>      return (
>          <div className={styles.checkboxWrapper} onClick={() => onFilterChange(option, !selected)} data-testid="checkbox-wrapper">
> -            <div className={wrapperClass} style={wrapperStyles} data-testid="checkbox">
> -                {selected && <i className="fa fa-check" style={checkStyles}  data-testid="checkmark" />}
> +            {/* <div className={wrapperClass} style={wrapperStyles} data-testid="checkbox">
>
> please remove comments
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fntechgit/schedule-filter-widget/pull/6#pullrequestreview-900466896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATURXEBF45NDRHBEV4SSORDU6I6ANANCNFSM5P55U43Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-05 02:04 UTC, santipalenque requested changes

2022-03-05 02:31 UTC, dequeMai commented
This is short hand hex for transparent color. 8 digit hex includes alpha
value. 4 digit is short hand.

On Fri, Mar 4, 2022, 8:05 PM Santi ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/filter-group/index.module.scss
> <https://github.com/fntechgit/schedule-filter-widget/pull/6#discussion_r820016357>
> :
>
> > @@ -4,6 +4,9 @@
>    .title {
>      display: flex;
>      justify-content: space-between;
> +    width: 100%;
> +    border: 0;
> +    background-color: #0000;
>
> please use transparent background
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fntechgit/schedule-filter-widget/pull/6#pullrequestreview-900856464>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATURXEBAP36DEMHR2EE2DJ3U6K6MTANCNFSM5P55U43Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-05 02:37 UTC, santipalenque approved these changes

2022-03-07 12:03 UTC, merged